### ISSUE TITLE
Control through Home app/Siri?

### ISSUE THREAD

**Issue by reparteeanimal** [magic7s/homebridge-ohmconnect#2]
Beyond just using the OhmHour, could this plug-in be given the power for the Home app/Siri to see and take commands to turn on/off? So it makes it a normal smart plug for Apple households without Google or Amazon hubs?

**Comment by magic7s** [comment]
You can use this to trigger automations. When it is a "Power Saving Hour" the ohmconnect sensor will open. Use that as a trigger in Home App to "turn off a smart plug" as an example.
